//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_type")]
pub enum ChannelType {
    #[sea_orm(string_value = "direct")]
    Direct,
    #[sea_orm(string_value = "dummy")]
    Dummy,
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "voice")]
    Voice,
    #[sea_orm(string_value = "stage")]
    Stage,
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "forum")]
    Forum,
}
